baseURL = "/"
languageCode = "vi-VN"
defaultContentLanguage = "vi"

title = "Hugo Learn Documentation"
theme = "hugo-theme-learn"
themesdir = "./themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/dinhnguyen/fobiz-manual/edit/master/content/"
  description = "Hướng dẫn sử dụng hệ thống Fobiz"
  author = "Mathieu Cornic"
  showVisitedLinks = true
  disableBreadcrumb = true
  disableNextPrev = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.vi]
title = "Documentation for Hugo Learn Theme"
weight = 1
languageName = "English"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fas fa-cog'></i> Fobiz admin"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-camera'></i> Showcases"
# url = "showcase"
# weight = 11

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
# identifier = "hugodoc"
# url = "https://gohugo.io/"
# weight = 20

# [[Languages.en.menu.shortcuts]]
# name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
# url = "/credits"
# weight = 30